# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  # Roots
  default:
    cmds:
      - nix develop
    silent: true
    desc: "run default Nix Shell"

  bruno:
    cmd: nix develop .#bruno
    silent: true
    desc: "run Nix Shell for Bruno"

  # Backend
  backend-dev:
    cmds:
      - fastapi dev ./backend/main.py
    silent: true
    desc: "run development server for the backend"
